import Head from "next/head";
import Image from "next/image";
import LandingPage from "../components/home/LandingPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {/* <!-- Favicons --> */}
        <link href="img/favicon.png" rel="icon" />
        <link href="img/apple-touch-icon.png" rel="apple-touch-icon" />

        {/* <!-- Google Fonts --> */}
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700"
          rel="stylesheet"
        />

        {/* <!-- Bootstrap CSS File --> */}
        <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

        {/* <!-- Libraries CSS Files --> */}
        <link
          href="lib/font-awesome/css/font-awesome.min.css"
          rel="stylesheet"
        />
        <link href="lib/animate/animate.min.css" rel="stylesheet" />
        <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet" />
        <link
          href="lib/owlcarousel/assets/owl.carousel.min.css"
          rel="stylesheet"
        />
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet" />

        {/* <!-- Main Stylesheet File --> */}
        <link href="css/style.css" rel="stylesheet" />

        {/* <!-- ======================================================= */}
        {/* Theme Name: Riveting */}
        {/* Author: TecJar.pro */}
        {/* ======================================================= --> */}

        {/* <!--======================================== */}
        {/* Eatery CSS */}
        {/* ==========================================--> */}
        <link rel="stylesheet" href="eatery/css/bootstrap.min.css" />
        <link rel="stylesheet" href="eatery/css/font-awesome.min.css" />
        <link rel="stylesheet" href="eatery/css/animate.css" />
        <link rel="stylesheet" href="eatery/css/owl.carousel.css" />
        <link rel="stylesheet" href="eatery/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="eatery/css/magnific-popup.css" />

        {/* <!-- MAIN CSS --> */}
        <link rel="stylesheet" href="css/templatemo-style.css" />
        {/* <!--eatery end--> */}

        {/* <!--======================================= */}
        {/* Creative css */}
        {/* =======================================--> */}
        {/* <!-- Google font --> */}
        <link
          href="https://fonts.googleapis.com/css?family=Arbutus"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round"
          rel="stylesheet"
        />

        {/* <!-- Bootstrap --> */}
        {/* <link
          type="text/css"
          rel="stylesheet"
          href="creative/css/bootstrap.min.css"
        /> */}
      </Head>

      <main>
        <LandingPage />
      </main>
    </div>
  );
}
